### ISSUE TITLE
No Sound when receiving Messages

### ISSUE THREAD

**Issue by panteLx** [ShadyThGod/altus#12]
Hi Sir!

First of all thx for that great app. 
Unfortunately Notifications wont work at all for me (even without sound)

See yah

**Comment by panteLx** [comment]
EDIT: Sometimes the sound is working but most of the time it wont.

**Comment by ShadyThGod** [comment]
Hey, glad you liked the app! I would like to know what OS you are using and what version of Altus you are using. Please let me know and I will look into the issue

**Comment by panteLx** [comment]
My System: https://i.imgur.com/fMqJHDu.png (OS Windows 10 Build 17763)
Altus V. 2.0.0

**Comment by ShadyThGod** [comment]
Could you show me your tab settings?

**Comment by panteLx** [comment]
https://i.imgur.com/4Sg33Ja.png Using multi instance

**Comment by ShadyThGod** [comment]
Okay that's weird. It worked when I tested it on my Windows 10 machine.

**Comment by panteLx** [comment]
Fun Fact its working on one instance but the second one isnt working at all 

Also what does the notification setting do? Didnt receive notifications via Terminal or smth like that.

**Comment by panteLx** [comment]
> Okay that's weird. It worked when I tested it on my Windows 10 machine.

Maybe its a bug caused by the second instance...

**Comment by ShadyThGod** [comment]
> Also what does the notification setting do? Didnt receive notifications via Terminal or smth like that.

It's supposed to show proper push notifications. It doesn't show through the terminal.

**Comment by ShadyThGod** [comment]
> Fun Fact its working on one instance but the second one isnt working at all

Do notifications work in that or do they not work at all?

**Comment by panteLx** [comment]
On one instance sound notifications work on the second one i didnt receive any notification...

also didnt get a single push notification ... :/ just the sound

**Comment by panteLx** [comment]
little update, i cant even hear sounds on one instance (audio msg). - didnt receive the notifications aswell on this instance...

**Comment by ShadyThGod** [comment]
I tested with two instances on my machine, and sound was working on both of them but push notifications didn't work. Push notifications seem to work on every other platform however

**Comment by panteLx** [comment]
deleted and added the buggy instance again... now sound works on both instances... weird bug :D

**Comment by ShadyThGod** [comment]
Weird thing happened when I was testing. I sent a message from my account on one instance to the account on second instance and a push notification showed up. But sending from second to first instance didn't do anything

**Comment by ShadyThGod** [comment]
> deleted and added the buggy instance again... now sound works on both instances... weird bug :D

Huh but still need to look into the push notification issue. I unfortunately don't have access to my proper PC today so I'll do that tomorrow. Sorry to make you wait, but I ensure you I'll fix this

**Comment by panteLx** [comment]
> > deleted and added the buggy instance again... now sound works on both instances... weird bug :D
> 
> Huh but still need to look into the push notification issue. I unfortunately don't have access to my proper PC today so I'll do that tomorrow. Sorry to make you wait, but I ensure you I'll fix this

No problem bro :) Great work at all!

**Comment by ShadyThGod** [comment]
@panteLx I tried testing again today, and notifications were working for both of my tabs. Could you try removing and re-adding the tabs, maybe?

**Comment by panteLx** [comment]
Its working for now. Push notification still not but anything else is working fine.

**Comment by panteLx** [comment]
One question, is the client updating automatically

**Comment by ShadyThGod** [comment]
> One question, is the client updating automatically

Unfortunately that is not possible for me right now. Auto-updates requires code signing and for that I'd have to buy a certificate. I'm just a student and don't really have the money to invest in a certificate.

**Comment by ShadyThGod** [comment]
> Its working for now. Push notification still not but anything else is working fine.

Again, that is just plain weird. Push notifications seem to be working on my main machine as well as a VM that I set up. I don't know how to reproduce this. Can you try to uninstall and re-install?

**Comment by panteLx** [comment]
I reinstalled/updated it to v2.0.1 but push notifications still don't work :/

**Comment by ShadyThGod** [comment]
> I reinstalled/updated it to v2.0.1 but push notifications still don't work :/

Huh. I have no idea how to fix this. Because it works in my testing.

**Comment by panteLx** [comment]
Well... Lets close that issue for now :P Till we find a solution.

**Comment by ShadyThGod** [comment]
> Well... Lets close that issue for now :P Till we find a solution.

I'll keep it open. Maybe somebody else can help find a solution.

**Comment by ShadyThGod** [comment]
@panteLx you should try out the latest release ([v2.0.5](https://github.com/shadythgod/altus/releases/2.0.5)). I have updated the Electron binary to 4.1.1. This might fix your problem

**Comment by panteLx** [comment]
It's finally fixed :3
