### ISSUE TITLE
Provide an option to disable Custom Titlebar (a.k.a. CSD) on Linux

### ISSUE THREAD

**Issue by cgonzalez** [ShadyThGod/altus#14]
I'm using Altus since 1.2.x version. I've just updated to 2.0.2 and now the app is using custom titlebar (a.k.a. CSD). This change is very unfortunate for KDE Plasma users, for several reasons:

* Can't resize the main window (since there is no border). I have to use a custom key + mouse combination (Alt + right click drag).
* Doesn't respect global titlebar button configurations (In plasma you can use a global menubar or a special button in the titlebar for the app menu).
* Main window has no shadows under KWin (KDE Plasma's window manager).
* Borderless apps appears on ALL "activities" (or desktop workspaces), breaking my workflow.

This is Altus 2.0.2 in KDE Plasma. Note the lack of borders and shadows (it's hard to resize the main window):
![altus_csd](https://user-images.githubusercontent.com/66578/54433015-8ef1cd80-4709-11e9-9dd2-12f1aca27651.png)

This is Altus after disabling the "No border" option in the window manager (ergo forcing native window decorations). Note the duplicated title, menubar (app menu is embebed in the second button from left to right in the titlebar) and minimize/maximize/close buttons:
![altus_no_csd](https://user-images.githubusercontent.com/66578/54433020-944f1800-4709-11e9-8bcd-cf13266b5035.png)

Is it possible to add a **configuration option** for disabling Custom Titlebar? The classical Electron titlebar from Altus 1.2.x works fine on KDE Plasma.

**Comment by ShadyThGod** [comment]
Thanks for making me aware of this. I will work on a fix as soon as possible. It's late here right now, so I'll work on this tomorrow but I'll make sure it's quick. This won't be too hard to fix.

**Comment by ShadyThGod** [comment]
[v2.0.3](https://github.com/ShadyThGod/altus/releases/tag/2.0.3) should have the fix for your issue

**Comment by cgonzalez** [comment]
Than you! v2.0.3 works like a charm :)
