### ISSUE TITLE
Altus - Ransomware Detection

### ISSUE THREAD

**Issue by Locked-Key** [ShadyThGod/altus#16]
![image](https://user-images.githubusercontent.com/44415788/55670848-c6dcd280-58bb-11e9-8991-0d81019e65f4.png)

It seems Bitdefender marks Altus as Ransomware

**Comment by Locked-Key** [comment]
However, re-opening Altus. Bitdefender doesn't detect and forced closed anymore.

**Comment by Locked-Key** [comment]
Nevermind. It still detects and gets forced closed by Bitdefender

**Comment by ShadyThGod** [comment]
I can assure you this is a false positive. I don't even know why this is happening. All of the source code used in my app is public. Before publishing, I do not change anything in the code. If you want to check you can manually build the app yourself. No other antivirus seems to do this with Altus.

**Comment by ShadyThGod** [comment]
[Here is the link to the VirusTotal scan for Altus.exe](https://www.virustotal.com/latest-scan/9d452fc7762e673461688ea07faa4e091929085f8b716d610d6b2460312f6bd5)

As you will see, the only AV that flags anything is Trapmine which, let's be honest, is an obscure AV that might not be correct.

I think the reason for some of these false positives is that my app is unsigned and controls some files on a device which might make the AV to think that it is somehow malicious.

Again, I can assure that my app is safe to use and is not malicious. If you have doubt, you can check the repository, and even manually build the app. I would recommend that you put Altus into the exceptions list, but if you do not want to, then I can understand.

**Comment by Locked-Key** [comment]
No worries, I understand that your app is clean. It's just that average people might get scared so I reported for potential fix to avoid future false positive scan :)

**Comment by psychicevolution** [comment]
Having similar issue on W10 with ESET Nod32 on my bussiness workstation.

The AV blocks the following website.

> Time;Scanner;Object type;Object;Detection;Action;User;Information;Hash;First seen here
07/04/2019 16:07:20;HTTP filter;file;http://now.daphnesik.icu/?utm_term=6677155101263530368&clickverify=1&utm_content=fdc2c69a9cafac9c9b9190a197979195ba88b8ccbecabcbd8b8688b18f8483b5a7babab98ebe8c8db3838081eae6eae1e9f8f9e9fbb2eceffbfef1e3ef97a595ad84878e828acca48c80cee1d4d3e4d7cefbf8f9989e908e97f3f0c0f6c6cdc7facbf9f9f6ffcccdc2a9;JS/Adware.Agent.AF application;connection terminated;AVL01\ROTELLAM;Event occurred during an attempt to access the web by the application: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe (FA54A877738E69C2E998CF1B173E8ECDDE82F2F5).;B44D7D30039C77ED0BA49285E10C023C061E570C;
> 

After that the application starts but is unusable: it keeps "reloading" forever the frontend at about 1s intervals, making impossible to perform any action.

**Comment by ShadyThGod** [comment]
@psychicevolution I don't even know how that shady link pops up in my app, there is literally no mention of such a site or any other site that could redirect to such a site in my app. That might be something wrong with your workstation that you might want to check. Also, I would recommend you only download from GitHub so you can ensure safe releases.

About the infinite reloading, it is a sloppy workaround for loading the dark theme before generating the frontend because if it loads after generating the frontend, you won't be able to use it until refreshing. I had to do this because synchronous file loading using fs from the main.js keeps breaking after building the app. I am trying to find a way to load it synchronously which won't break after building. I will work on this ASAP and a fix will probably be available in the next version.

**Comment by psychicevolution** [comment]
> @psychicevolution I don't even know how that shady link pops up in my app, there is literally no mention of such a site or any other site that could redirect to such a site in my app. That might be something wrong with your workstation that you might want to check. Also, I would recommend you only download from GitHub so you can ensure safe releases.
> 
> About the infinite reloading, it is a sloppy workaround for loading the dark theme before generating the frontend because if it loads after generating the frontend, you won't be able to use it until refreshing. I had to do this because synchronous file loading using fs from the main.js keeps breaking after building the app. I am trying to find a way to load it synchronously which won't break after building. I will work on this ASAP and a fix will probably be available in the next version.

Thanks @ShadyThGod for the quick and clear reply. 

I am going to check where this link comes from. I have never had this kind of links popping up before i installed the Altus App downloaded from https://shadythgod.github.io/altus/ - first things first, i will uninstall the app and reinstall from git repo.

bye, Marco

**Comment by psychicevolution** [comment]
Quick update: version 2.1.0 from git repo works almost fine. The version i was using before was the 2.0.4 from  https://shadythgod.github.io/altus/, my bad. Thanks again

**Comment by ShadyThGod** [comment]
I'm glad it's working for you! By the way, did you find out where that link caught in your AV came from?
