### ISSUE TITLE
Add Autostart?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ShadyThGod/altus#18]
Yeah, I know, everyone could do that himself, but I'm sure, there are some people, who don't know how.
For those, it would be nice, if either the installer or the application offer some button or checkbox or something, which enables/disables Autostart for the app.

**Comment by ShadyThGod** [comment]
Thanks for the suggestion. This has been on my mind for a while but I never ended up doing this. I will implement this in the next version.

**Comment by ThexXTURBOXx** [comment]
Very nice! A lot of people will be very thankful! :)

**Comment by ShadyThGod** [comment]
This feature has been implemented in [v2.2.0](https://github.com/ShadyThGod/altus/releases/tag/2.2.0)

**Comment by ThexXTURBOXx** [comment]
Works for me on Windows! Thank you very much :)
