### ISSUE TITLE
Threema Support

### ISSUE THREAD

**Issue by Timeo04** [ShadyThGod/altus#19]
I would suggest to add Support for Threema Web. Threema is a very cool App for chatting, secure and with many functions. Threema Web is avalible under web.threema.ch  .
C.B.

**Comment by ShadyThGod** [comment]
Thank you, @Timeo04, for your suggestion. However, unfortunately, this is something that is not possible. Altus was made only for WhatsApp Web and I do not plan on adding any other services to this as the whole app was built keeping WhatsApp Web in mind. For me to add another service, I would have to re-work the whole app from the start. Again, I am sorry, but this won't happen.

**Comment by ShadyThGod** [comment]
I would recommend you suggesting this to [Franz](https://github.com/meetfranz/franz) or [RamBox](https://github.com/ramboxapp/community-edition) as they are already built for supporting multiple services.

If you have any JavaScript experience, you can create a plugin (i.e. service) for [Franz](https://github.com/meetfranz/plugins) yourself.
