### ISSUE TITLE
Update Chrome to 36

### ISSUE THREAD

**Issue by MathiasJZ** [ShadyThGod/altus#21]
altus want update chrome to v36.
But I aleady have installed chrome v73.0.3683.103

the other thing:
altus starts also at the system start. How can I start altus when i need it?
Greetings,
Mathias

**Comment by ShadyThGod** [comment]
Please update to the latest version of Altus which is v2.2.0. It has a setting which you can enable to start Altus on system start.

**Comment by ShadyThGod** [comment]
If you have a Mac -> use [this link](https://github.com/ShadyThGod/altus/releases/download/2.2.0/Altus-2.2.0.dmg)

If you have Windows -> use [this link](https://github.com/ShadyThGod/altus/releases/download/2.2.0/Altus-Setup-2.2.0.exe)

**Comment by MathiasJZ** [comment]
I have installed already version 2.2.0.
Altus asks me to install Chrome 36+ anyway.
thank you for your link.
So where I can change settings?
I don’t ike to start altus with every system start.
greetings,
Mathias

**Comment by ShadyThGod** [comment]
This is how you can disable the setting:
![](https://i.imgur.com/E5dBsrk.gif)

**Comment by MathiasJZ** [comment]
Once again:
Where in the settings I can disble it?
Greetings,Mathias

Am 17. April 2019 11:30:10 schrieb Aman Harwara <notifications@github.com>:

**Comment by ShadyThGod** [comment]
I think since you are directly replying through e-mail instead of checking my reply on GitHub, your e-mail client didn't show you the GIF of the instructions I provided.

Anyways, here is the link to the GIF which has the instructions: [https://i.imgur.com/E5dBsrk.gif](https://i.imgur.com/E5dBsrk.gif)
