### ISSUE TITLE
The app freezes

### ISSUE THREAD

**Issue by roydeboys** [ShadyThGod/altus#22]
I am using a mac os and whenever i am trying to use more than 1 instance of whatsapp its freezing and then it stays the same even after restarting the app.

**Comment by ShadyThGod** [comment]
Please specify your system information a bit more?

Also, let me know which version of Altus you are using.

Because, when I test on my macOS, Altus 2.2.0 is working fine with even 3 instances.

**Comment by roydeboys** [comment]
i was using 2.3.0 
system info : macbook pro  version :10.14.4 (18E226) Mojave
i will try with 2.2.0 and let u know if it works thank for the response :)

**Comment by roydeboys** [comment]
Hi shady i installed v2.2.0 release and its working perfectly fine for 3 tabs as far as i checked. Thank you and great work on the project :)
