### ISSUE TITLE
on every start --> "there is an update" on Altus 2.3.1 on Win 10

### ISSUE THREAD

**Issue by Thomi1234** [ShadyThGod/altus#24]
Hi on every first start (i have autostart enabled) comes there is an update, please klick to update WhatsApp..
After klicking it, it keeps the same Version. Than the update hint is gone up to the next start of my PC
I tried complete delete Altus and reinstalled it (fresh) nothing helps..

**Comment by ShadyThGod** [comment]
That update hint is about WhatsApp and not Altus. Clicking it does nothing. Also, it is something that I do not have any control of.

**Comment by Thomi1234** [comment]
Ah, okay. Strange because in Version 2.3.0 i can`t remember that hint
from WhatsApp. Maybe it goes away sometimes :) Thanks

2019-05-21 8:39 GMT+02:00, Aman Harwara <notifications@github.com>:
