### ISSUE TITLE
No notification on windows 10

### ISSUE THREAD

**Issue by yawks** [ShadyThGod/altus#26]
Even enabling Notifications, no notification are visible when receiving a new message on Windows 10.
However the badge & the sound are working and the number of unread messages correctly appear in the left upper tab.

My windows version is :
Windows 10 enterprise, version 1803 (build 17134.765)

**Comment by raulcraveiro** [comment]
I'm having the same problem. I don't receive any notification when I receive a new message :/

**Comment by Zoli1972** [comment]
Having the same here.

**Comment by ShadyThGod** [comment]
If you don't use multiple accounts, I recommend switching back to [v1.2.4](https://github.com/ShadyThGod/altus/releases/tag/1.2.4). It is an older but very functional version with themes and notifications working perfectly.

**Comment by ShadyThGod** [comment]
I have just released [v1.3.0](https://github.com/ShadyThGod/altus/releases/tag/1.3.0) which is based of an older version, but with additional changes. This version doesn't have multiple account support, but it does have almost every other feature. Theses issues shouldn't occur in v1.3.0

**Comment by ShadyThGod** [comment]
Fixed in [v3.0](https://github.com/ShadyThGod/altus/releases/tag/3.0.0).
