### ISSUE TITLE
please update Chrome.....

### ISSUE THREAD

**Issue by MathiasJZ** [ShadyThGod/altus#31]
I get the message that i need to update Chrome into 49+.
But I installed the newest Chrome 75.0.3770.142
In this case I can't use altus anymore cause WhatsApp chat wont start.

![Altus](https://user-images.githubusercontent.com/20886303/61768369-92980e00-ade7-11e9-8634-669dd385ea61.JPG)

![Chrome](https://user-images.githubusercontent.com/20886303/61768375-9592fe80-ade7-11e9-9ed0-6249bd5470b3.JPG)

**Comment by Leozn17** [comment]
please add this commit to the autoupdate function

**Comment by ShadyThGod** [comment]
Fixed in [v2.3.3](https://github.com/ShadyThGod/altus/releases/tag/2.3.3)
