### ISSUE TITLE
[Feature Request] Hide the tabs

### ISSUE THREAD

**Issue by raulcraveiro** [ShadyThGod/altus#32]
I would love the possibility to hide the tabs, because it takes so much space and I only have one account.

**Comment by ShadyThGod** [comment]
Thanks for the suggestion; I really liked the idea. I have implemented this in [v2.4.0](https://github.com/ShadyThGod/altus/releases/tag/2.4.0)

**Comment by insign** [comment]
A option in Settings and/or button aside stories button is an ideia.
