### ISSUE TITLE
WhatsApp audio messages have no sound when playing them

### ISSUE THREAD

**Issue by Zoli1972** [ShadyThGod/altus#33]
Hi,

When I play audio messages I have got via WhatsApp, they have no audio. Where can I set an audio device for playback insinde the app? I didn't find any settings for that. 

Z.

**Comment by ShadyThGod** [comment]
There should be a setting when you create a new instance called "Enable Sound". It might not have been enabled in your instance. Click the settings icon near the name of the tab, and then make sure the setting "Enable Sound" is on.

![Tab Settings](https://i.imgur.com/7FaUHQm.png)

**Comment by ShadyThGod** [comment]
Fixed in [v3.0](https://github.com/ShadyThGod/altus/releases/tag/3.0.0).
