### ISSUE TITLE
Remove the menu bar on Windows

### ISSUE THREAD

**Issue by raulcraveiro** [ShadyThGod/altus#35]
Hello! 

Is there a way to remove the menu bar on Windows version?

![image](https://user-images.githubusercontent.com/5623492/65367438-f8e2b680-dc07-11e9-8bdf-88de962a2f55.png)

**Comment by ValentinVoigt** [comment]
@raulcraveiro You might be affected by #36. Please make sure you're using the latest version, which is 2.4.0. Check the README for links to that specific version.

**Comment by raulcraveiro** [comment]
As @ShadyThGod mentioned on #36, I'm having problems with notification on the 2.4.0, that's why I'm using the 1.3.0 version.
