### ISSUE TITLE
Check for updates suggests downgrade to 1.3.0

### ISSUE THREAD

**Issue by ValentinVoigt** [ShadyThGod/altus#36]
Thanks for your good work. I love Altus for having a dark themed WhatsApp desktop client!

Today I let Altus check for updates. It said there was a new version 1.3.0.

![Altus_EZeqvOAIFG](https://user-images.githubusercontent.com/1874562/65586916-443cf200-df85-11e9-8433-41c413a3f211.png)

I installed the program and was disappointed by the title bar being back to Windows' default light theme. I was about to submit a bug report, when I noticed your README actually suggests 2.4.0 as most recent version.

Also, I'm quite sure #35 is related to that.

**Comment by ShadyThGod** [comment]
Actually **v1.3.0** is for those are having issues with **v2.4.0** (that version was freezing for some people)

The actual current version is v2.4.0. If it works fine for you, then continue using it.

**Comment by ValentinVoigt** [comment]
Thanks for the clarification.

I'd still consider this a bug. Your choice of course.

**Comment by ShadyThGod** [comment]
It's not really a bug. _v1.3.0_ has the basic menu because I stripped down the software so it wouldn't freeze. I'm trying recreating the newer versions which doesn't freeze, but I don't know when I'll be able to get it working.
