### ISSUE TITLE
Please extent your support for android device

### ISSUE THREAD

**Issue by s1-ranjan** [ShadyThGod/altus#37]
There is a very good project for Android device called `[Disa](https://disa.im)`, it would be great if a plugin for `[Disa](https://disa.im)` can be created from scratch.

**Comment by ShadyThGod** [comment]
I'm sorry but WhatsApp is already available on Android. If you want to customize it, then I'm pretty sure there are modded ones available. Altough, I think WhatsApp is against modded apps on Android and banning accounts that use those apps.

It doesn't make any sense to port Altus to Android, as WhatsApp is already available on Android.
