### ISSUE TITLE
3.0.0 cannot be started on Mac OS

### ISSUE THREAD

**Issue by graspalme** [ShadyThGod/altus#39]
Immediately after starting the app, it crashes

**Comment by ShadyThGod** [comment]
I think this might an issue that occurs after packaging the app, because the app works fine when using `npm start`

**Comment by ShadyThGod** [comment]
So I've found the issue. I'll update the .dmg file and let you know.

**Comment by ShadyThGod** [comment]
I have updated the dmg file with the fix. You can download it from the releases page or here:
[Altus-3.0.0.dmg](https://github.com/ShadyThGod/altus/releases/download/3.0.0/Altus-3.0.0.dmg)
