### ISSUE TITLE
Ubuntu 18.10 not starting issue

### ISSUE THREAD

**Issue by Dafnik** [ShadyThGod/altus#4]
Altus is not starting on Ubuntu 18.10. I tried the AppImage and the .deb file. This is the response I'm getting if I launch it via the console.
`Segmentation fault (core dumped)`

**Comment by ShadyThGod** [comment]
Could you let me know that command you are using in the terminal?

**Comment by Dafnik** [comment]
Additionally I would like to say that Altus isn't launching via the desktop shortcut at all. So I tried it via the terminal. I will send the command later.

**Comment by Dafnik** [comment]
I executed this command: "/opt/Altus/altus" %U after I installed it via the deb package.

**Comment by Dafnik** [comment]
There is a related issue in electron. [electron#13972](https://github.com/electron/electron/issues/13972)

**Comment by ShadyThGod** [comment]
It could be that this is a 18.10 issue because the app works properly on 18.04.

I am unable to test it on 18.10 yet because I haven't received the update yet.
