### ISSUE TITLE
Broken Dark Theme in Altus v3.1.0

### ISSUE THREAD

**Issue by Melvin-Abraham** [ShadyThGod/altus#40]
I have always loved the WhatsApp Dark Theme in Altus but recently in version 3.1.0 (which I clean installed from the `release` section), the dark theme seems to be broken.

The chat bubble is white while the foreground text is light grey in color which looks completely clumsy.

![Altus Dark Theme](https://user-images.githubusercontent.com/26056183/68964912-86a1e300-0800-11ea-9188-f129ad37cbd8.jpg)

_(Broken Default Dark Theme)_

**P.S.:** Custom Theme worked for me though... 😉

**Comment by ShadyThGod** [comment]
Try going to the Themes window and clicking the "Update Base Themes" button and let me know if the issue still persists with the dark theme.

**Comment by Melvin-Abraham** [comment]
Well, I tried clicking it but there seems to be no difference. **Moreover**, it does not give any feedback or progress indication while updating... :(

**Comment by ShadyThGod** [comment]
Usually, the "update" happens quick enough to not show any visual signs of loading.

**Comment by ShadyThGod** [comment]
However, can you please try "Update Base Themes" and then pressing `Ctrl+Shift+R` to force reload the window?
Because, the base dark theme seems to be working just fine for me.

**Comment by Melvin-Abraham** [comment]
Nope. It failed. Still the same...

**Comment by ShadyThGod** [comment]
If you are on Windows, close Altus and then go to `%appdata%\altus`, delete the `themes.json` file and restart the app. Try this and let me know

**Comment by Melvin-Abraham** [comment]
That worked fine. Thanks, @ShadyThGod.
