### ISSUE TITLE
Retain geometry in local storage?

### ISSUE THREAD

**Issue by LimpingNinja** [ShadyThGod/altus#43]
I'm not sure if this is common or simply related to the Desktop Manager and OS i'm using, I'm currently running the .AppImage on KDE/Manjaro Linux and every start-up Altus starts in full-screen. Really a minor annoyance, an added step on a 5K monitor that is not needed. It would be nice if window geometry was retained.

**Comment by ShadyThGod** [comment]
[v.3.3.0](https://github.com/ShadyThGod/altus/releases/tag/3.3.0)
