### ISSUE TITLE
WhatsApp works with Google Chrome 36+

### ISSUE THREAD

**Issue by Dafnik** [ShadyThGod/altus#7]
After you start Altus you can't access WhatsApp anymore. Because WhatsApp needs Google Chrome 36+. I think it's possible to fix this issue if we update the electron version again.
![Here is the message I get](https://user-images.githubusercontent.com/16242839/49998244-13f70a80-ff94-11e8-9df2-21308d5465a6.png)

**Comment by ShadyThGod** [comment]
I have made the necessary changes required, in the package.json. I am having issues getting electron-builder to work, but if you can build the app yourself, it should work now.

**Comment by ShadyThGod** [comment]
> I have made the necessary changes required, in the package.json. I am having issues getting electron-builder to work, but if you can build the app yourself, it should work now.

I tried updating electron to 3.0.12 but the problem persists. Will have to look more in depth.

**Comment by ShadyThGod** [comment]
It seems like this could be some error on WhatsApp's part because a few other apps like mine are also facing the issue.

**Comment by ShadyThGod** [comment]
Commit [6481be3](https://github.com/ShadyThGod/altus/commit/6481be3abeda7022d5a13d0f07704985e8cd901f) has a fix for this. However, some times you might need to reload the page using `Ctrl`+`Shift`+`R`

**Comment by Dafnik** [comment]
Seems to be fixes, thank you!
