### ISSUE TITLE
Turning off tray icon causes JavaScript error

### ISSUE THREAD

**Issue by dylanmcdougall** [ShadyThGod/altus#9]
Disabling tray icons causes the following error whenever the application is launched.
![screenshot_2018-12-27_17-12-25](https://user-images.githubusercontent.com/40744272/50496028-1da05980-09fb-11e9-800a-3c2e6e63252f.png)
Clicking 'OK' results in the application launching as normal.

The error seems to be caused by `trayIcon.destroy();` in `main.js`
Removing it doesn't appear to have any negative effects.

**Comment by ShadyThGod** [comment]
Thanks for letting me know. I've added a fix in [59affb5](https://github.com/ShadyThGod/altus/commit/59affb5d7a6e4ed9bbf5094a89dfff5cd8b2a9e2)
